# 使用 Ubuntu 20.04 作为基础镜像
FROM ubuntu:20.04

# 更新软件包列表并安装必要的依赖
RUN apt-get update && apt-get install -y \
    curl \
    software-properties-common \
    && rm -rf /var/lib/apt/lists/*

# 安装 Nginx
RUN apt-get update && apt-get install -y nginx

# 安装 Node.js 20.x
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
RUN apt-get install -y nodejs

# 创建工作目录
WORKDIR /app

# 复制项目代码到工作目录
COPY . /app

# 安装 Node.js 依赖
RUN npm install

# 构建 Vue.js 3 应用
RUN npm run build

# 配置 Nginx 的默认 HTML 目录
RUN rm -rf /var/www/html && \
    ln -s /app/dist /var/www/html

# RUN if [ -f /etc/nginx/conf.d/default.conf ]; then rm /etc/nginx/conf.d/default.conf; fi

# ADD default.conf /etc/nginx/conf.d/

# 暴露 Nginx 端口
EXPOSE 80

# 启动 Nginx 服务
CMD ["nginx", "-g", "daemon off;"]
