# 使用 CentOS 7 最小化镜像作为基础镜像
FROM centos/systemd as builder

# 维护者信息
LABEL maintainer="zakingwong"

# 更新centos镜像地址
RUN cd /etc/yum.repos.d/ && \
    sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* 

RUN yum install wget

RUN wget -O /etc/yum.repos.d/CentOS-Base.repo https://mirrors.aliyun.com/repo/Centos-vault-8.5.2111.repo && \
    yum clean all && \
    yum makecache

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash

RUN nvm install stable

# 更新系统软件包并安装所需依赖
RUN yum update -y && \
    yum install -y \
        epel-release \
        nginx \
    yum clean all && \
    rm -rf /var/cache/yum

# 设置工作目录
WORKDIR /app

# 复制项目代码
COPY . /app

# 在 Node.js 依赖安装步骤前后添加 RUN 命令
RUN echo "Current working directory: $(pwd)"
RUN npm ci
RUN echo "Node.js version: $(node --version)"
RUN echo "npm version: $(npm --version)"


# 构建 Vue.js 3 项目
RUN npm run build

# 使用 Nginx 官方镜像作为运行时镜像
FROM nginx:latest

# 复制构建结果到 Nginx 容器
COPY --from=builder /app/dist /usr/share/nginx/html

# 设置容器名称
LABEL com.example.container-name="treasure-container"

# 检查是否已经存在同名容器,如果存在则停止并删除
RUN if [ "$(docker ps -a -q -f name=treasure-container)" ]; then \
        echo "Container 'treasure-container' already exists, stopping and removing it"; \
        docker stop treasure-container && docker rm treasure-container; \
    fi

# 暴露 Nginx 默认端口 80
EXPOSE 80

# 启动 Nginx 服务
CMD ["nginx", "-g", "daemon off;"]
